### ISSUE TITLE
Could you provide code of the project?

### ISSUE THREAD

**Issue by JingYang321** [Tianshu996/METSC#1]
Thank you very much

**Comment by Tianshu996** [comment]
Please be patient; the patent corresponding to this project is under review, and we will publish the code at a suitable time after the patent review is completed. You can reproduce the project yourself, and if you encounter any problems, you can contact us in time.

**Comment by JingYang321** [comment]
Ok,Thanks



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 13, 2023 22:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Tianshu996/METSC] Could you provide code of the project? (Issue#1)




 
Please be patient; the patent corresponding to this project is under review, and we will publish the code at a suitable time after the patent review is completed. You can reproduce the project yourself, and if you encounter any problems, you can contact us in time.
